DROP TABLE room_type CASCADE;
DROP TABLE room_image CASCADE;
DROP TABLE room CASCADE;
DROP TABLE person CASCADE;
DROP TABLE building_image CASCADE;
DROP TABLE building CASCADE;
DROP TABLE hotel_image CASCADE;
DROP TABLE hotel CASCADE;
